---
title: "GID Day presentation"
author: "Dr. ASRI"
date: "2022-11-15"
output: 
  pdf_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r}
library(sp)
library(spdep)
library(sf)
library(tidyverse)
library(INLA)
```


## données 

```{r}

```


## Carte

```{r}
dz2 <- geodata::gadm("DZ", level = 0, path = getwd())


#full<- full_join(dzsf, data, by = "Wilaya")
#fullsp<- as_Spatial(full)
```



## Modélisation 

```{r}
m <- dz2
plot(m)
```

```{r}
m <- m %>%
  st_as_sf() %>%
  st_cast("POLYGON") %>%
  mutate(area = st_area(.)) %>%
  arrange(desc(area)) %>%
  slice(1)
```
```{r}
ggplot(m) + geom_sf() + theme_bw()
```

```{r}
m <- m %>% st_transform(25830)
ggplot(m) + geom_sf() + theme_bw() + coord_sf(datum = st_crs(m))
```

```{r}

```


```{r}
p <- st_as_sf(data.frame(long = data_precip2$LON, lat = data_precip2$LAT),
              coords = c("long", "lat"))
st_crs(p) <- st_crs(4326)
p <- p %>% st_transform(25830)
data_precip2[, c("x", "y")] <- st_coordinates(p)
```


```{r}
d <- data_precip2

ind <- st_intersects(m, p)
d <- d[ind[[1]], ]
```

```{r}
ggplot(m) + geom_sf() + coord_sf(datum = st_crs(m)) +
  geom_point(data = d, aes(x = x, y = y)) + theme_bw()
```
```{r}
ggplot(d) +
  geom_histogram(mapping = aes(x = s)) +
  facet_wrap(~MO, ncol = 1) +
  theme_bw()
```

```{r}
library(viridis)

ggplot(m) + geom_sf() + coord_sf(datum = NA) +
  geom_point(
    data = d, aes(x = x, y = y, color = s),
    size = 2
  ) +
  labs(x = "", y = "") +
  scale_color_viridis() +
  facet_wrap(~MO) +
  theme_bw()
```

```{r}
ggplot(d, aes(x = MO, y = s, group = LON, color = LON)) +
  geom_line() +
  geom_point(size = 2) +
  scale_x_continuous(breaks = c(2015, 2016, 2017)) +
  theme_bw() + theme(legend.position = "none")
```

```{r}
coo <- cbind(d$x, d$y)
bnd <- inla.nonconvex.hull(st_coordinates(m)[, 1:2])
mesh <- inla.mesh.2d(
  loc = coo, boundary = bnd,
  max.edge = c(100000, 200000), cutoff = 1000,
)
```

```{r}
mesh$n
```
```{r}
plot(mesh)
points(coo, col = "red")
```
```{r}
spde <- inla.spde2.pcmatern(
  mesh = mesh, alpha = 2, constr = TRUE,
  prior.range = c(10000, 0.01), # P(range < 10000) = 0.01
  prior.sigma = c(3, 0.01) # P(sigma > 3) = 0.01
)
```

```{r}
timesn <- length(unique(d$MO))
indexs <- inla.spde.make.index("s",
  n.spde = spde$n.spde,
  n.group = timesn
)
lengths(indexs)
```

```{r}
group <- d$MO - min(d$MO) + 1
A <- inla.spde.make.A(mesh = mesh, loc = coo, group = group)
```

```{r}
bb <- st_bbox(m)
x <- seq(bb$xmin - 1, bb$xmax + 1, length.out = 50)
y <- seq(bb$ymin - 1, bb$ymax + 1, length.out = 50)
dp <- as.matrix(expand.grid(x, y))
plot(dp, asp = 1)
```
```{r}
p <- st_as_sf(data.frame(x = dp[, 1], y = dp[, 2]),
  coords = c("x", "y")
)
st_crs(p) <- st_crs(25830)
ind <- st_intersects(m, p)
dp <- dp[ind[[1]], ]
plot(dp, asp = 1)
```

```{r}
dp <- rbind(cbind(dp, 1), cbind(dp, 2), cbind(dp, 3))
head(dp)
```

```{r}
coop <- dp[, 1:2]
groupp <- dp[, 3]
Ap <- inla.spde.make.A(mesh = mesh, loc = coop, group = groupp)
```

```{r}
stk.e <- inla.stack(
  tag = "est",
  data = list(y = d$s),
  A = list(1, A),
  effects = list(data.frame(b0 = rep(1, nrow(d))), s = indexs)
)

stk.p <- inla.stack(
  tag = "pred",
  data = list(y = NA),
  A = list(1, Ap),
  effects = list(data.frame(b0 = rep(1, nrow(dp))), s = indexs)
)

stk.full <- inla.stack(stk.e, stk.p)
```

```{r}
rprior <- list(theta = list(prior = "pccor1", param = c(0, 0.9)))
```

```{r}
formula <- y ~ 0 + b0 + f(s,
  model = spde, group = s.group,
  control.group = list(model = "ar1", hyper = rprior)
)
```

```{r}
res <- inla(formula,
  data = inla.stack.data(stk.full),
  control.predictor = list(
    compute = TRUE,
    A = inla.stack.A(stk.full)
  )
)
```

```{r}
summary(res)
```
```{r}
list_marginals <- list(
"b0" = res$marginals.fixed$b0,
"precision Gaussian obs" =
res$marginals.hyperpar$"Precision for the Gaussian observations",
"range" = res$marginals.hyperpar$"Range for s",
"stdev" = res$marginals.hyperpar$"Stdev for s",
"rho" = res$marginals.hyperpar$"GroupRho for s"
)

```

```{r}
marginals <- data.frame(do.call(rbind, list_marginals))
marginals$parameter <- rep(names(list_marginals),
  times = sapply(list_marginals, nrow)
)
```

```{r}
ggplot(marginals, aes(x = x, y = y)) + geom_line() +
  facet_wrap(~parameter, scales = "free") +
  labs(x = "", y = "Density") + theme_bw()
```
```{r}
index <- inla.stack.index(stack = stk.full, tag = "pred")$data
```

```{r}
dp <- data.frame(dp)
names(dp) <- c("x", "y", "time")

dp$pred_mean <- res$summary.fitted.values[index, "mean"]
dp$pred_ll <- res$summary.fitted.values[index, "0.025quant"]
dp$pred_ul <- res$summary.fitted.values[index, "0.975quant"]
```

```{r}
library(reshape2)
dpm <- melt(dp,
  id.vars = c("x", "y", "time"),
  measure.vars = c("pred_mean", "pred_ll", "pred_ul")
)
head(dpm)
```

```{r}
ggplot(m) + geom_sf() + coord_sf(datum = NA) +
  geom_tile(data = dpm %>% filter(variable != "pred_mean"), aes(x = x, y = y, fill = value)) +
  labs(x = "", y = "") +
  facet_wrap(variable ~ time) +
  scale_fill_viridis("précipitations") +
  theme_bw()
```

```{r}
ggplot(m) + geom_sf() + coord_sf(datum = NA) +
  geom_tile(data = dpm %>% filter(variable == "pred_mean"), aes(x = x, y = y, fill = value)) +
  labs(x = "", y = "") +
  facet_wrap(variable ~ time) +
  scale_fill_viridis("précipitations") +
  theme_bw()
```

